#!/bin/bash
#
# supervisord   This scripts turns supervisord on
#
# Author:       Mike McGrath <mmcgrath@redhat.com> (based off yumupdatesd)
#
# chkconfig:	- 95 04
#
# description:  supervisor is a process control utility.  It has a web based
#               xmlrpc interface as well as a few other nifty features.
# processname:  supervisord
# config: /etc/supervisord.conf
# pidfile: /var/run/supervisord.pid
#
# inspired by https://github.com/Supervisor/initscripts

# source function library
. /etc/rc.d/init.d/functions

# source system settings
[ -e /etc/sysconfig/supervisord ] && . /etc/sysconfig/supervisord

STOP_TIMEOUT=${STOP_TIMEOUT-60}
OPTIONS="${OPTIONS--c /etc/supervisord.conf}"

RETVAL=0

start() {
	echo -n $"Starting supervisord: "
	if [ -e "/var/lock/subsys/supervisord" ]; then
		echo "ALREADY STARTED"
		return 1
	fi

	daemon supervisord $OPTIONS
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/supervisord
}

stop() {
	echo -n $"Stopping supervisord: "
	killproc -d ${STOP_TIMEOUT} supervisord
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/supervisord
}

restart() {
	stop
	start
}

reload() {
	supervisorctl $OPTIONS reload
	RETVAL=$?
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|force-reload)
	restart
	;;
	reload)
	reload
	;;
  condrestart)
	[ -f /var/lock/subsys/supervisord ] && restart
	;;
  status)
	status supervisord
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
	exit 1
esac

exit $RETVAL
